#!/usr/bin/env python3
"""
Performance Analysis Script for HDMapping Execution Times

This script reads elapsed time data from CSV files generated by the PowerShell measurement script
and provides statistical analysis and visualization.

Usage:
    python analyze_performance.py <csv_file>
    
Example:
    python analyze_performance.py REVISION_total_time.csv
"""

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import argparse

def load_and_validate_data(csv_file):
    """Load CSV data and perform basic validation."""
    try:
        # Read the CSV file
        df = pd.read_csv(csv_file)
        
        # Check if the expected column exists
        if 'elapsed_time' not in df.columns:
            raise ValueError(f"Expected column 'elapsed_time' not found in {csv_file}")
        
        # Remove any non-numeric values and convert to float
        df['elapsed_time'] = pd.to_numeric(df['elapsed_time'], errors='coerce')
        
        # Handle optional new columns
        if 'total_seconds' in df.columns:
            df['total_seconds'] = pd.to_numeric(df['total_seconds'], errors='coerce')
        if 'total_time_formatted' in df.columns:
            # Keep as string, no conversion needed
            pass
        
        # Remove NaN values
        original_count = len(df)
        df = df.dropna(subset=['elapsed_time'])
        cleaned_count = len(df)
        
        if original_count != cleaned_count:
            print(f"Warning: Removed {original_count - cleaned_count} invalid entries")
        
        if df.empty:
            raise ValueError(f"No valid elapsed time data found in {csv_file}")
        
        return df
    
    except FileNotFoundError:
        raise FileNotFoundError(f"CSV file not found: {csv_file}")
    except Exception as e:
        raise Exception(f"Error reading CSV file: {str(e)}")

def calculate_statistics(data):
    """Calculate comprehensive statistics for the elapsed time data."""
    stats = {
        'count': len(data),
        'min': data.min(),
        'max': data.max(),
        'mean': data.mean(),
        'median': data.median(),
        'std_dev': data.std(),
        'variance': data.var(),
        'q25': data.quantile(0.25),
        'q75': data.quantile(0.75),
        'iqr': data.quantile(0.75) - data.quantile(0.25),
        'range': data.max() - data.min(),
        'cv': (data.std() / data.mean()) * 100 if data.mean() != 0 else 0  # Coefficient of variation
    }
    return stats

def print_statistics(stats, csv_file, total_seconds=None, total_time_formatted=None):
    """Print formatted statistics to console."""
    print(f"\n{'='*60}")
    print(f"PERFORMANCE ANALYSIS REPORT")
    print(f"File: {csv_file}")
    print(f"{'='*60}")
    
    if total_seconds is not None and total_time_formatted is not None:
        print(f"\nTOTAL EXECUTION TIME:")
        print(f"  Total Seconds:    {total_seconds:>8.2f} seconds")
        print(f"  Formatted Time:   {total_time_formatted:>8}")
    
    print(f"\nBASIC STATISTICS:")
    print(f"  Sample Count:     {stats['count']:>8,}")
    print(f"  Minimum:          {stats['min']:>8.4f} seconds")
    print(f"  Maximum:          {stats['max']:>8.4f} seconds")
    print(f"  Range:            {stats['range']:>8.4f} seconds")
    
    print(f"\nCENTRAL TENDENCY:")
    print(f"  Mean:             {stats['mean']:>8.4f} seconds")
    print(f"  Median:           {stats['median']:>8.4f} seconds")
    
    print(f"\nVARIABILITY:")
    print(f"  Standard Dev:     {stats['std_dev']:>8.4f} seconds")
    print(f"  Variance:         {stats['variance']:>8.4f} seconds²")
    print(f"  Coeff. of Var:    {stats['cv']:>8.2f}%")
    
    print(f"\nQUARTILES:")
    print(f"  25th Percentile:  {stats['q25']:>8.4f} seconds")
    print(f"  75th Percentile:  {stats['q75']:>8.4f} seconds")
    print(f"  IQR:              {stats['iqr']:>8.4f} seconds")

def create_visualizations(data, csv_file):
    """Create and save histogram and other visualizations."""
    # Set up the plotting style
    plt.style.use('seaborn-v0_8')
    sns.set_palette("husl")
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    fig.suptitle(f'Performance Analysis: {Path(csv_file).stem}', fontsize=16, fontweight='bold')
    
    # 1. Histogram with density curve
    axes[0, 0].hist(data, bins=30, alpha=0.7, color='skyblue', edgecolor='black', density=True)
    
    # Add kernel density estimation
    from scipy import stats
    kde = stats.gaussian_kde(data)
    x_range = np.linspace(data.min(), data.max(), 100)
    axes[0, 0].plot(x_range, kde(x_range), 'r-', linewidth=2, label='KDE')
    
    axes[0, 0].axvline(data.mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: {data.mean():.4f}s')
    axes[0, 0].axvline(data.median(), color='green', linestyle='--', linewidth=2, label=f'Median: {data.median():.4f}s')
    axes[0, 0].set_xlabel('Elapsed Time (seconds)')
    axes[0, 0].set_ylabel('Density')
    axes[0, 0].set_title('Distribution of Elapsed Times')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)
    
    # 2. Box plot
    box_plot = axes[0, 1].boxplot(data, patch_artist=True)
    box_plot['boxes'][0].set_facecolor('lightblue')
    axes[0, 1].set_ylabel('Elapsed Time (seconds)')
    axes[0, 1].set_title('Box Plot of Elapsed Times')
    axes[0, 1].grid(True, alpha=0.3)
    
    # 3. Time series (if we have sequence data)
    axes[1, 0].plot(range(len(data)), data, marker='o', markersize=3, alpha=0.7)
    axes[1, 0].axhline(data.mean(), color='red', linestyle='--', alpha=0.8, label=f'Mean: {data.mean():.4f}s')
    axes[1, 0].set_xlabel('Iteration Number')
    axes[1, 0].set_ylabel('Elapsed Time (seconds)')
    axes[1, 0].set_title('Elapsed Time Sequence')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)
    
    # 4. Cumulative distribution
    sorted_data = np.sort(data)
    y_values = np.arange(1, len(sorted_data) + 1) / len(sorted_data)
    axes[1, 1].plot(sorted_data, y_values, marker='o', markersize=3)
    axes[1, 1].axvline(data.median(), color='green', linestyle='--', alpha=0.8, label=f'Median: {data.median():.4f}s')
    axes[1, 1].set_xlabel('Elapsed Time (seconds)')
    axes[1, 1].set_ylabel('Cumulative Probability')
    axes[1, 1].set_title('Cumulative Distribution Function')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)
    
    # Adjust layout and save
    plt.tight_layout()
    
    # Save the plot
    output_file = f"{Path(csv_file).stem}_analysis.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\nVisualization saved as: {output_file}")
    
    # Show the plot
    plt.show()

def save_statistics_report(stats, csv_file, total_seconds=None, total_time_formatted=None):
    """Save detailed statistics to a text file."""
    output_file = f"{Path(csv_file).stem}_statistics_report.txt"
    
    with open(output_file, 'w') as f:
        f.write(f"PERFORMANCE ANALYSIS REPORT\n")
        f.write(f"File: {csv_file}\n")
        f.write(f"Generated: {pd.Timestamp.now()}\n")
        f.write(f"{'='*60}\n\n")
        
        if total_seconds is not None and total_time_formatted is not None:
            f.write(f"TOTAL EXECUTION TIME:\n")
            f.write(f"  Total Seconds:    {total_seconds:>8.2f} seconds\n")
            f.write(f"  Formatted Time:   {total_time_formatted:>8}\n\n")
        
        f.write(f"BASIC STATISTICS:\n")
        f.write(f"  Sample Count:     {stats['count']:>8,}\n")
        f.write(f"  Minimum:          {stats['min']:>8.4f} seconds\n")
        f.write(f"  Maximum:          {stats['max']:>8.4f} seconds\n")
        f.write(f"  Range:            {stats['range']:>8.4f} seconds\n\n")
        
        f.write(f"CENTRAL TENDENCY:\n")
        f.write(f"  Mean:             {stats['mean']:>8.4f} seconds\n")
        f.write(f"  Median:           {stats['median']:>8.4f} seconds\n\n")
        
        f.write(f"VARIABILITY:\n")
        f.write(f"  Standard Dev:     {stats['std_dev']:>8.4f} seconds\n")
        f.write(f"  Variance:         {stats['variance']:>8.4f} seconds²\n")
        f.write(f"  Coeff. of Var:    {stats['cv']:>8.2f}%\n\n")
        
        f.write(f"QUARTILES:\n")
        f.write(f"  25th Percentile:  {stats['q25']:>8.4f} seconds\n")
        f.write(f"  75th Percentile:  {stats['q75']:>8.4f} seconds\n")
        f.write(f"  IQR:              {stats['iqr']:>8.4f} seconds\n\n")
        
        # Performance insights
        f.write(f"PERFORMANCE INSIGHTS:\n")
        f.write(f"  Most operations complete within: {stats['q75']:.4f} seconds\n")
        f.write(f"  95% complete within: {stats['mean'] + 2*stats['std_dev']:.4f} seconds\n")
        f.write(f"  Consistency (low CV = good): {'Good' if stats['cv'] < 20 else 'Moderate' if stats['cv'] < 50 else 'Poor'}\n")
        
    print(f"Detailed report saved as: {output_file}")

def main():
    """Main function to run the performance analysis."""
    parser = argparse.ArgumentParser(description='Analyze performance data from HDMapping execution times')
    parser.add_argument('csv_file', help='Path to the CSV file containing elapsed time data')
    parser.add_argument('--no-plot', action='store_true', help='Skip generating plots')
    parser.add_argument('--no-save', action='store_true', help='Skip saving detailed report')
    
    args = parser.parse_args()
    
    try:
        # Load and validate data
        print(f"Loading data from: {args.csv_file}")
        df = load_and_validate_data(args.csv_file)
        data = df['elapsed_time']
        
        # Extract total execution time if available
        total_seconds = None
        total_time_formatted = None
        if 'total_seconds' in df.columns and not df['total_seconds'].isna().all():
            total_seconds = df['total_seconds'].iloc[0]
        if 'total_time_formatted' in df.columns and not df['total_time_formatted'].isna().all():
            total_time_formatted = df['total_time_formatted'].iloc[0]
        
        # Calculate statistics
        stats = calculate_statistics(data)
        
        # Display results
        print_statistics(stats, args.csv_file, total_seconds, total_time_formatted)
        
        # Save detailed report
        if not args.no_save:
            save_statistics_report(stats, args.csv_file, total_seconds, total_time_formatted)
        
        # Create visualizations
        if not args.no_plot:
            try:
                create_visualizations(data, args.csv_file)
            except ImportError as e:
                print(f"\nWarning: Could not create plots due to missing dependencies: {e}")
                print("Install required packages: pip install matplotlib seaborn scipy")
            except Exception as e:
                print(f"\nWarning: Could not create plots: {e}")
        
        print(f"\nAnalysis completed successfully!")
        
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
